### ISSUE TITLE
`pydantic` weekly project plan (Sydney Runkle) - August 5th, 2024

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10055]
## Background

Following on the heels of #9994, I'm going to continue with this public weekly plan approach.

The motivation behind tickets like these is to:

1. Communicate and coordinate with the community
2. Summarize and track weekly developments in `pydantic`
3. Help me / our team organize and prioritize issues

## Last Week's Highlights

* https://github.com/pydantic/pydantic/pull/10013
* https://github.com/pydantic/pydantic/pull/10009
* https://github.com/pydantic/pydantic/pull/9998
* https://github.com/pydantic/pydantic/pull/9980

### Contributors

Thanks to @changhc for the sustained work on complex number support!
Thanks to @kc0506 for working on some hard to track down bugs!

## My plans for this week

For the first half of the week, I'm going to focus on wrapping up performance improvements in `pydantic`. The second half of the week, I'll be pivoting to union serialization fixes.

- [ ] https://github.com/pydantic/pydantic/issues/8652
- [ ] https://github.com/pydantic/pydantic/issues/9905
- [ ] https://github.com/pydantic/pydantic/issues/9688
- [ ] https://github.com/pydantic/pydantic/issues/9956

If I manage to finish all of the above (which would be wonderful), but is not likely, I'll spend the rest of the week tackling small bugs / issues that have been put on the back burner for some of this larger scale work.

### `pydantic`

- [ ] https://github.com/pydantic/pydantic/pull/9770
- [ ] https://github.com/pydantic/pydantic/pull/9863
- [ ] https://github.com/pydantic/pydantic/pull/10029
- [ ] https://github.com/pydantic/pydantic/pull/10030

### `pydantic-core`

Nothing at the moment, but I'm sure this will change. Ping me if you're looking for a review!

## Feedback

I'd love to get some feedback from the community / other contributors here. What else would be helpful for you to see on weekly reports like these?

Other sections I think could be valuable:
* high priority issues
* good first issues

**Comment by changhc** [comment]
Hi Syndey, thank you for posting weekly reports. I think it would be great to see high priority issues that the community can help with, or even just issues that are triaged but the team is not going to work on immediately. Having such a list would be quite helpful as the community will not need to figure out which issues folks can pick up.

**Comment by sydney-runkle** [comment]
@changhc,

Sure thing! In the meantime, you can filter by `help wanted` or `good first issue`. That being said, I'll go through the issues this week and come up with a good list :).

**Comment by sydney-runkle** [comment]
Managed to make some forward progress on the union fixes with the following PRs:

Would still like to implement some sort of smarter mode that utilizes a type check on the input data to give preference to a matching serializer. I anticipate being able to do this for v2.9, hopefully next week 👍
