### ISSUE TITLE
pydantic weekly project plan (Sydney Runkle) - August 12th, 2024

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10109]
## Background

Following on the heels of #10055, I'm going to continue with this public weekly plan approach.

The motivation behind tickets like these is to:

1. Communicate and coordinate with the community
2. Summarize and track weekly developments in `pydantic`
3. Help me / our team organize and prioritize issues

## Last Week's Highlights

* https://github.com/pydantic/pydantic/pull/10029
* https://github.com/pydantic/pydantic/pull/10030
* https://github.com/pydantic/pydantic/pull/10064

## My plans for this week

This week, I'm going to wrap up the union serialization fixes discussed in #9688, and spend the remainder of my development time trying to figure out the best way forward with #10074. Next week, I'll pivot to readying for the v2.9 release 🚀. I'm also looking forward to doing lots of reviewing, both on `pydantic` and `pydantic-core` as we prep for this release.

I anticipate putting up a docs PR or two as always 📝.

### Issues

- [x] #9688
- [ ] #10074

### PRs in progress

- [x] https://github.com/pydantic/pydantic-core/pull/1398
- [x] https://github.com/pydantic/pydantic-core/pull/1400
- [x] https://github.com/pydantic/pydantic/pull/10112
- [x] https://github.com/pydantic/pydantic-core/pull/1403
- [x] https://github.com/pydantic/pydantic/pull/10137
- [x] https://github.com/pydantic/pydantic/pull/10136
- [x] https://github.com/pydantic/pydantic/pull/10123 
- [x] https://github.com/pydantic/pydantic/pull/10113
- [x] https://github.com/pydantic/pydantic-core/pull/1397
- [x] https://github.com/pydantic/pydantic-core/pull/1405

Whenever the above two high prio issues are fixed, I can move to other work in the v2.9 milestone 🚀.

## Review Queue

Lots to review this week - will try to front load providing this feedback.

### `pydantic`

- [x] #9654 
- [x] #9863
- [ ] #10005 
- [x] #10077
- [x] #10082 
- [x] #10092 
- [x] #10100 
- [x] #10102 
- [x] #10103
- [x] #10121

### `pydantic-core`

- [x] https://github.com/pydantic/pydantic-core/pull/1373
- [ ] https://github.com/pydantic/pydantic-core/pull/1399
- [ ] https://github.com/pydantic/pydantic-core/pull/1359

## Feedback

I'd love to get some feedback from the community / other contributors here. What else would be helpful for you to see on weekly reports like these?

Other sections I think could be valuable:
* high priority issues
* good first issues

**Comment by sydney-runkle** [comment]
See https://github.com/pydantic/pydantic/issues/9688#issuecomment-2284286319 re union serialization fixes
