### ISSUE TITLE
v2.9 Checklist

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10189]
## Intro

We're shooting for a v2.9 beta release early next week - August 26th or 27th, preferably. This release cycle, we emphasized working on performance improvements, union serialization fixes, documentation, JSON schema fixes, and a variety of new features.

## Pre-beta TODOs

- [x] https://github.com/pydantic/pydantic/issues/8208 via https://github.com/pydantic/pydantic/pull/10094
- [x] https://github.com/pydantic/pydantic/issues/10173
- [x] https://github.com/pydantic/pydantic/issues/8693
- [x] https://github.com/pydantic/pydantic/issues/9394
- [x] Clean up v2.9.0 milestone to reflect things that have been pushed to v2.10
- [x] v1 patch release + bundle into v2 pre v2.9.0b1 -- will do by the end of the week (August 23rd)

### Needing review:

- [x] https://github.com/pydantic/pydantic-core/pull/1415

### Optional, or pushed to v2.10

- [x] https://github.com/pydantic/pydantic/issues/7252
- [ ] https://github.com/pydantic/pydantic/issues/9670
- [ ] https://github.com/pydantic/pydantic/issues/6885
- [ ] https://github.com/pydantic/pydantic/issues/9871
- [ ] Finish up https://github.com/pydantic/pydantic/pull/10100 - will require new tests, docs updates, issue triaging
- [ ] https://github.com/pydantic/pydantic/issues/8142
- [ ] Make a decision on https://github.com/pydantic/pydantic/pull/10005
- [ ] https://github.com/pydantic/pydantic/issues/7353 and related url / constraint issues

## Post-beta TODOs

- [x] https://github.com/pydantic/pydantic/issues/10239
- [x] `pydantic-core` docs update via https://github.com/pydantic/pydantic-core/issues/1389
- [x] v2.9 blog post to socialize changes + improvements - need to collect some performance stats from users
- [ ] Major update to docs examples page -- add 10 more or so

We can continue to update this list as things come up, but generally this should serve as a solid guideline for our high priority work in the next few days!

**Comment by sydney-runkle** [comment]
@Viicos,

Feel free to add the issues you'd like to complete that I may have missed to the checklist above

**Comment by sydney-runkle** [comment]
We've released [v2.9.0b1](https://pypi.org/project/pydantic/2.9.0b1/), so I'll be pivoting to the above docs updates re pre beta todos!

**Comment by sydney-runkle** [comment]
Update for folks following here - planning on the v2.9 release tomorrow! cc @Viicos :)
