### ISSUE TITLE
v2.10 - The Plan

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10349]
For v2.10, our focus will be on addressing several high-priority changes, feature requests, and a wide range of bug fixes.

While performance improvements were the main priority in v2.9, they will still be included in this release, but won't be the primary focus.

Regarding timeline, I found that a 2 month period was good. Let's shoot for the end of October for now, and we'll adjust as needed.

### More flexible validation of generics

* https://github.com/pydantic/pydantic/issues/10359
* https://github.com/pydantic/pydantic/issues/9414
* other similar issues, filter on https://github.com/pydantic/pydantic/labels/generics

* https://github.com/pydantic/pydantic/issues/9467
* https://github.com/pydantic/pydantic/issues/10315

## Feature Requests

* https://github.com/pydantic/pydantic/issues/9789
* https://github.com/pydantic/pydantic/issues/9619

EDIT: deferred until v2.11:
* https://github.com/pydantic/pydantic/issues/8394
* https://github.com/pydantic/pydantic/issues/9731

## Bug Fixes

I'm sure we'll work on many bugs that aren't listed here, but a few that come to mind at the moment are:

* https://github.com/pydantic/pydantic/issues/8232
* https://github.com/pydantic/pydantic/issues/7353 (and other url issues, we ran out of time for this in v2.9)
* https://github.com/pydantic/pydantic/issues/9683

I've collected some issues in https://github.com/pydantic/pydantic/milestone/19 to serve as a guideline for work during this milestone. I don't think we'll complete everything in the milestone within the projected time block, but this provides some insight into issues that we recognize as important enough to address in the short term.

If you have an issue / feature request that you'd like included in this release:

1. Leave a comment on this issue - we're happy to consider your suggestion. We're much more likely to prioritize a feature request / change if there's been demonstrated high demand (think 👍 reacts, comments, etc).
2. If you **really** want a feature request / change, please open a PR! That's the best way to fast track adoption 🐎. We're excited to collaborate with you 🚀 !

**Comment by gilmorera** [comment]
> What about https://github.com/pydantic/pydantic/issues/9686?
> 
> Did I miss this in the milestone?

Oh I see this is for pydantic-core.  Will it be part of the 2.10 release?

**Comment by sydney-runkle** [comment]
Probably won't get into v2.10 unless someone opens a PR with support for it - happy to review though! I've pinged DH re the most recent question to see if we can get the ball rolling there again.

**Comment by sydney-runkle** [comment]
Still TODO:

- [ ] Document https://github.com/pydantic/pydantic/issues/9686 (@sydney-runkle)
- [ ] Fix `AnyUrl` isinstance issue raised by @alexmojaki (@sydney-runkle is working on this)
- [ ] https://github.com/pydantic/pydantic/issues/9467 and related issues (@sydney-runkle)
- [ ] Merge `pydantic` PR for https://github.com/pydantic/pydantic/issues/9789
- [ ] Finish up `CoreMetadata` refactor PR
- [ ] Finish up `KeyError` `Generic` PR (@Viicos)

There's probably more, we can keep this up to date as we wrap things up in the next few days

**Comment by caniko** [comment]
What about #9782? I saw that it was postponed for v2.10

**Comment by Viicos** [comment]
> What about #9782? I saw that it was postponed for v2.10

We might take a look for 2.11. I'll take a look to gauge how much work it requires.

**Comment by Viicos** [comment]
@caniko, regarding PEP 695 support, are you running into issues with the new `type` syntax (https://github.com/pydantic/pydantic/issues/8984) or with the new generics syntax?

**Comment by caniko** [comment]
The new generics syntax works fine, I was referring to the new `type` syntax.

**Comment by sydney-runkle** [comment]
Hi friends! We've finished much of the above - going to close this as resolved, given that we've moved forward with the beta release.

We're a bit behind on PR reviews given this push to get things out, so we'll be catching up on those soon.
