### ISSUE TITLE
`pydantic` work plan for Sydney Runkle: September 23rd - September 27th, 2024

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#10468]
Keeping on with the more simple approach here.

My top priorities this week:

From last week, getting these across the line:

- [x] https://github.com/pydantic/pydantic/issues/9989
- [ ] https://github.com/pydantic/pydantic/issues/10315

Cracking on with v2.10 issues (the first two will take the vast majority of my time)

- [ ] https://github.com/pydantic/pydantic/issues/10299 - made some good progress here, see updates on the issue
- [ ] Working on namespace management improvements with @Viicos and @MarkusSintonen. Addressing https://github.com/pydantic/pydantic/issues/10074 through https://github.com/pydantic/pydantic/pull/10425 and other PRs.
- [x] Make an API decision on https://github.com/pydantic/pydantic/issues/9467 to implement next week

Documentation work:

- [x] https://github.com/pydantic/pydantic/issues/10251
- [ ] https://github.com/pydantic/pydantic-core/issues/1452
- [ ] Working on docs observability for internal analytics

I might (hopefully) get to:

- [ ] Following up on json schema building issues with refs / defs in https://github.com/pydantic/pydantic/issues/8271 

Not sure if it's super helpful for me to list a big queue of constantly changing TODOs for reviews here, so going to skip that for this week. Probably makes more sense to just do the reviews when they come up.

I do think it's helpful for me to keep an issue updated with my progress as the week comes along, so I'll do that here :).

**Comment by Kestranor** [comment]
Out of curiousity, will you be also integrating the recently released pydantic-core 2.24 in a coming release? If I see correctly, 2.23.4 is currently used, but unfortunately, the Python 3.11 build fails on pywheels (I created an issue ticket on the piwheels github to track it [here](https://github.com/piwheels/packages/issues/472). Thanks.

**Comment by Viicos** [comment]
pydantic-core releases are meant to work with a single version of Pydantic, and 2.24 is expected to be included in Pydantic 2.10 (no expected release date for now). Probably best to wait for piwheels to fix the build (if the issue is coming from them), so that you can use pydantic 2.9 on you Raspberry.

**Comment by Kestranor** [comment]
Makes sense, thanks for the response!

**Comment by sydney-runkle** [comment]
Though many of the above issues aren't closed, we made good progress on almost all of them last week, and I anticipate closing many of them by the end of this sprint (Friday).
