### ISSUE TITLE
Sydney Runkle's Work: Dec 2nd -> Dec 6th

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#11026]
This week, I'm planning on:

- [x] Releasing v2.10.3 with the fixes detailed in https://github.com/pydantic/pydantic/issues
  In particular, this requires me to dig into some url related fixes
- [ ] Get https://github.com/pydantic/pydantic/pull/10846 across the line
- [ ] Continue reviewing @MarkusSintonen's work on perf with schema cleaning - this was deferred while we worked on patch releases
- [ ] Resume reviews for other important new features like `exclude_if`, etc.
- [ ] Plan out v2.11 more concretely with a timeline
- [ ] Documentation PR - I'd like to hold myself accountable to one of these per week, even if it's small

I'll also be doing a good bit of work on `pydantic-ai`, mostly on the documentation front this week.
I'd also like to further familiarize myself with the API / codebase.

PRs for the week:

* https://github.com/pydantic/pydantic/pull/11028
* https://github.com/pydantic/pydantic/pull/11027
* https://github.com/pydantic/pydantic/pull/11035

**Comment by sydney-runkle** [comment]
Due to my unexpected attendance at a Boston AI conference late last week, lots of this has been pushed to this week 👍
