### ISSUE TITLE
Sydney Runkle's Work: Dec 9th - Dec 15th

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#11067]
This week, I'm planning on:

- [ ] Releasing v2.10.4 with any last fixes associated with v2.10
- [ ] Get https://github.com/pydantic/pydantic/pull/10846 across the line
- [ ] Continue reviewing @MarkusSintonen's work on perf with schema cleaning - this was deferred while we worked on patch releases
- [ ] Resume reviews for other important new features like `exclude_if`, etc.
- [ ] Plan out v2.11 more concretely with a timeline

I'll also be doing a good bit of work on `pydantic-ai` on the documentation + new model support fronts.
