### ISSUE TITLE
V1.10 release

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#4324]
To do/decide:
* [x] #2557 - **merged**
* [x] #2745 - needs some tweaks, but we need to decide if it's a good idea before V2
* [x] #2190 - **deferred**
* [x] cherry pick stuff from v1.9 branch, maybe just history #4350
* [x] #3346
* [x] #3593 -  **deferred**
* [x] #3946
* [x] #4028 - **API will change in v2**
* [x] #4354
* [x] #4216
* [x] #4191
* [x] #3941 - revert or fix
* [x] #4339
* [x] #4356

**Comment by samuelcolvin** [comment]
Ideally I'd like to get a pre-release of V1.10 out early next week.

If you have a change you'd like to be included in V1.10, please make sure your PRs are ready to merge and use the magic comment "please review" to assign us.

**Comment by DetachHead** [comment]
#4356 is ready to go i think

**Comment by satheler** [comment]
#4165 is ready to go i think

**Comment by invokermain** [comment]
#3674 would be amazing 🙏

**Comment by samuelcolvin** [comment]
> #3674 would be amazing pray

this is already merged, so will be included.

**Comment by samuelcolvin** [comment]
so are #4165 and #4356.
