### ISSUE TITLE
V2 beta 1 outstanding issues

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#5919]
Getting the beta out has taken longer than expected, but it's worth it - we're looking really good.

Still to do:
* [x] decide on https://github.com/pydantic/pydantic-core/pull/645, and test in pydantic
* [x] https://github.com/pydantic/pydantic-core/pull/646
* [x] #5920
* [x] https://github.com/pydantic/pydantic/issues/5914 - fixed in https://github.com/pydantic/pydantic-core/pull/651
* [x] https://github.com/pydantic/pydantic/issues/5918
* [x] Issue with `Config` reporting by @tiangolo while working on FastAPI #5921
* [x] I'd be more comfortable if we improved the coverage on `json_schema.py`, see [here](https://smokeshow.helpmanual.io/5f4g1p5r3y474i3o296d/d_2705a9c05af28909_json_schema_py.html) - currently it's bad, but probably requires @dmontagu to improve it as well as make sure the logic is correct
* [ ] What about the [discriminated union tests](https://github.com/pydantic/pydantic/blob/74539c9c0ff06016c1c058b658b57d855f66d7aa/tests/test_discriminated_union.py#L351-L354)  hat are `xfail`ing with enums - do we need to many any changes to enums/literals?
* [x] https://github.com/pydantic/pydantic-core/issues/649

**Comment by samuelcolvin** [comment]
To think about after release:
* [ ] https://github.com/pydantic/speedate/issues/34

**Comment by dmontagu** [comment]
Can we do [this](https://github.com/pydantic/pydantic/pull/5935/files#r1210388231) before the release?

Specifically, changing `from pydantic.annotated import GetCoreSchemaHandler` to `from pydantic.handlers import GetCoreSchemaHandler`. It seems @adriangb didn't mind the suggested change but didn't want to do in that PR. Making a note here before opening a PR for it.

**Comment by hramezani** [comment]
Closing this one. I moved the remaining issues to https://github.com/pydantic/pydantic/issues/6096
