### ISSUE TITLE
☝️ Pydantic Priorities

### ISSUE THREAD

**Issue by samuelcolvin** [pydantic/pydantic#7324]
In rough order of priority:

* [x] schema construction performance @adriangb
* [ ] #7322 - step by step over time
* [x] Fix the most annoying bits of Hooky - assigning someone when a maintainer creates an issue, adding a "Selected Assignee:" to issues, running when reopening issues, remove the 👍 on issues - @lig please can you work on this
* [x] JSON Schema name changes, #7209 - **Requires minor release**
* [ ] Validate String, https://github.com/pydantic/pydantic-core/pull/883 - **Requires minor release**
* [ ] documentation for [pydantic-core types](https://github.com/pydantic/pydantic-core/blob/main/python/pydantic_core/_pydantic_core.pyi), it's currently very incomplete
* [x] config flag to re-instate `int` -> `str` validation like v1, #6045 - **Requires minor release**
* [ ] #7323
* [ ] #7188 - **Requires minor release** let's not merge this until we're sure we're ready for another minor release
* [ ] https://github.com/pydantic/pydantic-core/pull/867 - **Requires minor release**
* [ ] generic ordering need warning and documentation, #6994 - **Requires minor release**
* [ ] allow python regexes, #7058 - **Requires minor release**
* [ ] release improvements, further work - https://github.com/pydantic/pydantic/pull/7244#discussion_r1304585752

**Comment by lig** [comment]
https://github.com/pydantic/pydantic/issues/7325 ?

**Comment by samuelcolvin** [comment]
> #7325 ?

Not a priority IMHO, and also slightly complicated as I commented.

**Comment by sydney-runkle** [comment]
Closing in favor of #7928, which contains all of the above unfinished items, as well as some others 😄

**Comment by M3gar00** [comment]
@sydney-runkle -- I'm trying to find where the tracking of the below issue is. This is the last time I see it mentioned. It's not mentioned in #7928, and seems to be completely dropped from the 2.6.0 milestone tracking.
```
config flag to re-instate int -> str validation like v1, https://github.com/pydantic/pydantic/issues/6045 - Requires minor release
```

**Comment by sydney-runkle** [comment]
@M3gar00,

We added the `coerce_numbers_to_str` flag to `ConfigDict` to support this request. See the docs [here](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.coerce_numbers_to_str).
