### ISSUE TITLE
Plugins Roadmap

### ISSUE THREAD

**Issue by lig** [pydantic/pydantic#7643]
- [ ] Add `plugins` label for Github Issues.
- [ ] Actually use `NewSchemaReturns` as `PydanticPluginProtocol.new_schema_validator` return type.
- [ ] Maybe use `TypedDict` for `NewSchemaReturns` instead of a `tuple`.
- [ ] Allow adding plugins in disabled state and provide an API for configuring and/or enabling a plugin by name in runtime.

**Comment by collerek** [comment]
Hi, are you planning to allow plugins also around serialization and not only validation?

**Comment by collerek** [comment]
@samuelcolvin What is your take on allowing plugins to wrap also serialization and not only validation? It would ease/enable transition to v2 for libraries like ormar: https://github.com/collerek/ormar

**Comment by sydney-runkle** [comment]
Closing this as stale, but happy to reopen if it's relevant in the future!
