### ISSUE TITLE
Pydantic Roadmap 🏎️ 

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#7928]
Below is a (by no means exhaustive) list of current priorities. Community feedback is more than welcome 🌟!

## Pydantic

- [x] Support validate strings, https://github.com/pydantic/pydantic-core/pull/883
- [x] #7845 (goes with #6994)
- [x] #7462
- [ ] Better documentation / consensus on desired behavior for #7577
- [x] #7864
- [ ] #7796
- [ ] #7946
- [ ] #6423

## Documentation
- [ ] Documentation for [`pydantic-core`](https://github.com/pydantic/pydantic-core/blob/main/python/pydantic_core/_pydantic_core.pyi) types
- [ ] #7576
- [ ] #3884
- [ ] #7323
- [ ] Improve cross links / code ref links in `pydantic` docs
- [ ] #7534

## Miscellaneous
- [ ] Release improvements https://github.com/pydantic/pydantic/pull/7244#discussion_r1304585752
- [ ] #7656
- [ ] #7188

**Comment by sydney-runkle** [comment]
Closing in favor of a milestone approach. Going to try that out for the next release 👍. Will return to the issue-hub strategy if we prefer that after some experimentation.
