### ISSUE TITLE
`2.5.0` Checklist

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#8028]
To be completed before we create the `2.5.0` release:

- [x] https://github.com/pydantic/pydantic/pull/8027
- [x] https://github.com/pydantic/pydantic/pull/8025
- [x] https://github.com/pydantic/pydantic/pull/8013
- [x] https://github.com/pydantic/pydantic/pull/7998 (@sydney-runkle, add docs)
- [x] https://github.com/pydantic/pydantic/pull/8001 (@sydney-runkle, add docs)
- [x] https://github.com/pydantic/pydantic/pull/8029
- [x] https://github.com/pydantic/pydantic/pull/8050
- [x] https://github.com/pydantic/pydantic/pull/8047
- [x] https://github.com/pydantic/pydantic/pull/8042
- [x] https://github.com/pydantic/pydantic/issues/8049

**Comment by alexmojaki** [comment]
So is 2.5 still going to support Python 3.7?

**Comment by hramezani** [comment]
> So is 2.5 still going to support Python 3.7?

2.5 will support Python 3.7. There is a [PR for dropping Python 3.7 support](https://github.com/pydantic/pydantic/pull/7188) but it won't be included in 2.5.

**Comment by sydney-runkle** [comment]
Right. We will drop 3.7 support for v2.6, most likely

**Comment by samuelcolvin** [comment]
Release of 2.5 is delayed while we fix #8049.

**Comment by sydney-runkle** [comment]
Closing this as all has been completed. Hoping to complete the beta release tomorrow 🤞
