### ISSUE TITLE
(WIP) high priority / high impact work 🚀 

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#9102]
If you're looking to contribute to `pydantic`, the fixes / features below are awesome, high-impact and high-demand features! We've also tagged many issues with `good first issue` that are a bit easier / less involved, so you can start there as well!

## Fixes

These should ideally be implemented in the upcoming minor release, though naturally, some take precedence over others.

- [x] Union issues (specifically, serialization choices)
- [x] Revisit unnecessary schema rebuilds sucking up schema build time, ex in #8628 (@sydney-runkle)
- [ ] https://github.com/pydantic/pydantic/issues/7353

## Features

These are high-impact or highly-requested features.

- [ ] `mode` parameter in `model_validate` logic, #9009
- [x] #4710 (there are also lots of other tz/zoneinfo/dt/date related issues that could be addressed)
- [ ] #8086
- [ ] Improve integration with popular data science libs (`numpy`, `polars`, `pandas`, etc)
- [ ] Support custom ordering of string (or other) constraint application, #8577
- [ ] #8922
- [ ] Custom validator ordering, #8277
- [ ] #8978
- [x] Add support for complex numbers https://github.com/pydantic/pydantic/issues/8555
- [ ] Revisit https://github.com/pydantic/pydantic/issues/8394
- [x] #4632
- [ ] TODO: comb through generic issues

## Changes / Important V3 Work

Work that doesn't fit under the umbrella for V2, but is on a high priority list for V3.

### High Impact

- [ ] Standardize APIs + behavior for alias usage for validation / serialization, #8379
- [ ] Reconcile differences between merging configs, #7271
- [ ] https://github.com/pydantic/pydantic/issues/7096 (see @dmontagu's comment)
- [ ] TODO: comb through generic issues more

### Low Impact

- [ ] Standardize error messages / types for similar operations, #9020
- [ ] Migrate highly specific types to `pydantic-extra-types`, #9071

**Comment by sydney-runkle** [comment]
@NeevCohen @Viicos @ornariece,

If you're looking for anything new to contribute to in the future, here's a fun collection :).

**Comment by Youssefares** [comment]
Keen to pick up #4710 👀

**Comment by sydney-runkle** [comment]
@Youssefares, you got it!

**Comment by CherrySuryp** [comment]
I've picked up #9071 ⚡️

**Comment by ldorigo** [comment]
You marked #8379  under V3, however, allowing to serialize by alias with a model config (not by default) should be in V2 (as indicated by last message in that issue)

**Comment by jammymalina** [comment]
> You marked #8379 under V3, however, allowing to serialize by alias with a model config (not by default) should be in V2 (as indicated by last message in that issue)

Is anyone working on this model config approach? If not I might be willing to pick it up but I might need some guidance from pydantic contributor.

**Comment by sydney-runkle** [comment]
Closing in favor of https://github.com/pydantic/pydantic/issues/10350
