### ISSUE TITLE
Milestones for integration with Numpy

### ISSUE THREAD

**Issue by austinyu** [pydantic/pydantic#9677]
### Initial Checks

- [X] I have searched Google & GitHub for similar requests and couldn't find anything
- [X] I have read and followed [the docs](https://docs.pydantic.dev) and still think this feature is missing

### Description

My team has been working with Pydantic for a while. It is a great library that makes our data validation and serialization tasks much easier. Thank you so much for the awesome work. Since our software heavily uses NumPy, we would like to request Pydantic support for integration with NumPy, as mentioned in the [high impact work](https://github.com/pydantic/pydantic/issues/9102). In this issue, I will summarize the features we would like Pydantic to support. Each feature includes some example use cases.

# Data Types Validation & Serialization

Introduction to [NumPy data type objects](https://numpy.org/doc/stable/reference/arrays.dtypes.html).

## Built-in NumPy Scalar Data Types
NumPy has extensive support for [integer, float, and complex numbers](https://numpy.org/doc/stable/user/basics.types.html#relationship-between-numpy-data-types-and-c-data-data-types). Supporting [scalar data types](https://numpy.org/doc/stable/reference/arrays.scalars.html#scalars) should be the first step. Currently, Pydantic treats these types as user-defined types, which throws validation errors because they do not implement `__get_pydantic_core_schema__`.

Metrics for successful implementation:
- Basic: Validate all float types as Python float, validate all int types as Python int. More discussion is needed for complex types.
- Bonus: Validate if the value of a number is within the bounds of its data type. e.g., `0 <= valid_uint8 <= 256`.
- Even better: Support [other types](https://numpy.org/doc/stable/reference/arrays.scalars.html#other-types) within scalar types.

Example:

```py
from pydantic import BaseModel
import numpy as np

class NpScalarModel(BaseModel):
    val_uint8: np.uint8
    val_float16: np.float16

valid_np = NpScalarModel.model_validate({
    'val_uint8': 255,
    'val_float16': 1.0
})

invalid_np = NpScalarModel.model_validate({
    'val_uint8': 3000000,
    'val_float16': 1.0
})
```

## Simple `dtype` objects.

NumPy data type objects are constructed by the [dtype constructor](https://numpy.org/doc/stable/reference/arrays.dtypes.html#specifying-and-constructing-data-types). Note that NumPy scalar data types discussed in the previous section are not instances of NumPy `dtype` objects.

Example:
```py
from typing import Annotated
from pydantic import BaseModel
import numpy as np

ByteDtype = np.dtype('b')
BigEndianUInt16 = np.dtype('>H')

class NpDtypeModel(BaseModel):
    val_byte: Annotated[int, ByteDtype]  # byte, native byte order
    val_uint16: Annotated[int, BigEndianUInt16]  # unsigned 16-bit integer, big-endian byte order
```

# Array Validation & Serialization

## Homogeneous Arrays

A homogeneous array contains values of the same data type.

Example:
```py
from typing import Annotated
from pydantic import BaseModel, NpField
import numpy as np

class ImageModel(BaseModel):
    img: Annotated[np.ndarray, NpField(shape=(100, 100), dtype=np.uint8)]
    mask: Annotated[np.ndarray, NpField(shape=(100, 100), dtype=bool)]
```

## Structured NumPy Arrays

[Structured arrays](https://numpy.org/doc/stable/user/basics.rec.html) are heterogeneous arrays with named fields whose data type is a composition of simpler data types. I am not entirely sure yet how NumPy structured dtypes and Pydantic models will be mutually convertible, but I feel like they share a lot of similarities conceptually.

Currently, the way our team tackles these problems is very hacky and unsafe. I am happy to share our very primitive solutions, but I am sure that other smart people have better solutions :)

### Affected Components

- [ ] [Compatibility between releases](https://docs.pydantic.dev/changelog/)
- [X] [Data validation/parsing](https://docs.pydantic.dev/concepts/models/#basic-model-usage)
- [X] [Data serialization](https://docs.pydantic.dev/concepts/serialization/) - `.model_dump()` and `.model_dump_json()`
- [X] [JSON Schema](https://docs.pydantic.dev/concepts/json_schema/)
- [ ] [Dataclasses](https://docs.pydantic.dev/concepts/dataclasses/)
- [ ] [Model Config](https://docs.pydantic.dev/concepts/config/)
- [ ] [Field Types](https://docs.pydantic.dev/api/types/) - adding or changing a particular data type
- [ ] [Function validation decorator](https://docs.pydantic.dev/concepts/validation_decorator/)
- [ ] [Generic Models](https://docs.pydantic.dev/concepts/models/#generic-models)
- [ ] [Other Model behaviour](https://docs.pydantic.dev/concepts/models/) - `model_construct()`, pickling, private attributes, ORM mode
- [ ] [Plugins](https://docs.pydantic.dev/) and integration with other tools - mypy, FastAPI, python-devtools, Hypothesis, VS Code, PyCharm, etc.

**Comment by sydney-runkle** [comment]
@austinyu,

Thanks for the detailed feature request here. I've added this to our v2.9.0 milestone!

**Comment by sneakers-the-rat** [comment]
found this when searching around for a different issue - OP may want to check out https://github.com/p2p-ld/numpydantic <3

**Comment by changhc** [comment]
Hi @sydney-runkle, I'd like to work on this issue and add more support for numpy types. I started with the simplest case "Built-in NumPy Scalar Data Types" and did some basic experiments. Now I have some ideas about what needs to be added and I would like to discuss the plan before proceeding. @austinyu Thank you for the clear description. I'd like to get feedback from you as well, specifically regarding error messages and validation strictness.

Do you think it's better that we actually check the types or at least make strict type checking as default? In @austinyu's code snippet, the field values are not in numpy types, and I suppose that you expect this validation to pass, essentially as you wrote,

> Basic: Validate all float types as Python float, validate all int types as Python int.

Based on my limited experience with numpy, types matter, especially the container types, since some operations can only work with numpy types or those operations suffer from performance issues when input values are not in numpy types. I know it's more than often that users want numpy data types but forget to convert the values to numpy types after reading them somewhere, e.g. loading numbers from from a text file, and then some operations just throw an error complaining incorrect data types, and then users need to find out where exactly they forgot to convert the types, which is quite annoying. This is the main reason that I think it might be good to make strict type checking the default behaviour. To relax this type checking, one can pass the option `strict=False` to the model so that only value validation is conducted.

This type checking comes with a cost. It makes the implementation much more complicated.

Relevant to this, what kind of error message do you expect to see? Again, if we treat all `np.(u)int` as built-in integers and `np.float` as built-in floats, it will be much easier, but I'm not sure if it's going to be nice enough. For instance, with this model
```py
class MyModel(BaseModel):
    val_uint8: np.uint8
```
a user gets an error with the following:
```py
valid_np = MyModel.model_validate({
    'val_uint8': 255.2,
})
```
saying that the value is expected to be an integer in [0, 255]. The user corrects this by removing the fraction, and then validation passes, even though the value is still not in the correct type. Then some unexpected errors might be raised again later on as I described above, which frustrates the user again.

Other than this, operation-wise, I'm thinking of making numpy-related things an extra feature of the package because numpy is quite chunky iirc and this might affect existing users, e.g. making their next built images unexpectedly large. What do you think @sydney-runkle?

**Comment by Viicos** [comment]
@changhc https://github.com/pydantic/pydantic/issues/10706 provides some context on how this could be achieved without using [custom types](https://docs.pydantic.dev/latest/concepts/types/#handling-third-party-types) as it is defined today.

I think it's best to wait a bit for our internal refactor to be complete, and it's also safer to wait for Numpy typing capabilities to be properly specified first:

- Numpy as a [`typing`](https://numpy.org/devdocs/reference/typing.html) module which is pretty new. It would be great to support these ones as well.
- There's some discussion around [typing support for shapes](https://github.com/numpy/numpy/issues/16544), which would involve type var tuples. It may be best to wait for it to be supported first.

**Comment by sneakers-the-rat** [comment]
see also https://github.com/pydantic/pydantic/issues/10161 - supporting numpy arrays would almost certainly involve full support of protocol classes :) 

There's the question re: what we want here, handling scalar `np.dtype` objects is one thing (with different mechanisms that would require either natively supporting in pydantic-core, or else expanding the plugin system to let us patch type annotations as an import side-effect), handling shape spec'd and dtype'd arrays is another. handling *useful* shape and dtype specs is actually a very different third thing, where you need to think about precision ranges, shape ranges, wildcard specs, and so on. 

The second and third thing are possible right now and it works pretty well: https://numpydantic.readthedocs.io/en/latest/

the type annotations not being `TypeVarTuple`s and otherwise compliant with the contemporary typing system is mostly a byproduct of `nptyping`'s history and now temporarily blocked by #10161 . Would love more details on the internal refactor because getting this fully implemented is sorta a passive blocker for me writing a paper about this and its application and scientific data standards, so please let me know how i can help <3

**Comment by psalvaggio** [comment]
FYI, I have implemented a NumPy adapter here: https://psalvaggio.github.io/scientific_pydantic/latest/api/scientific_pydantic/numpy/#scientific_pydantic.numpy.NDArrayAdapter

It captures the dtype and NDArray parts of this issue. For NDArray's it supports gt, ge, lt, le validation, as well as a fairly generic type specifier syntax.
