### ISSUE TITLE
v2.8 TODO - WIP

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#9753]
I'm hoping to get a beta release out mid week this week, with an official release out early next week. I'll be out of office June 6th-15th ish, and I'd like to offer some support for fixes, etc before I leave.

This is still a WIP, I'm working on reorganizing our milestones such that we can accelerate this release a bit (it's been a while). A fair number of bugs will be pushed to our v2.9.0 milestone. That release will primarily focus on:
1. Performance improvements in schema building
2. Fixes for union serialization
3. The aforementioned bugs being pushed to v2.9 that we've already designated as worthwhile to fix

### Python Support
- [x] Add `Python 3.13` support to `pydantic-core` and `jiter` (thanks @davidhewitt)
- [x] https://github.com/pydantic/pydantic/issues/9668
- [x] https://github.com/pydantic/pydantic/issues/9613

### Bug fixes / changes
- [ ] https://github.com/pydantic/pydantic/issues/9683 - edit, this would be nice to fix, but we can fix this in a patch release, so isn't critical for v2.8 (I thought we broke this after v2.7, but it's been around for a while)
- [x] https://github.com/pydantic/pydantic/issues/9536
- [x] https://github.com/pydantic/pydantic/issues/9744

### Packaging
- [ ] `speedate` patch release
- [ ] `pydantic-core` patch release

Update: we encountered some unexpected bugs when fixing some existing issues in `speedate`, so we've delayed the next release until we can get those fixed. This will be included in a 2.8.1 patch release soon!

## Official Release:
- [x] 2.8 blog post
- [x] Expand on `FastFail` docs
- [x] https://github.com/pydantic/pydantic/issues/9768

**Comment by sydney-runkle** [comment]
Marking as resolved. v2.8.1 will contain the new `speedate` as well as the serializer fix linked above.
