### ISSUE TITLE
`pydantic` weekly project plan (Sydney Runkle) - July 1, 2024

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#9804]
## Background

Inspired by the awesome work of @alamb, I'm going to try out a similar public [weekly plan](https://github.com/apache/datafusion/issues/11190) approach.

The motivation behind tickets like these is to:

1. Communicate and coordinate with the community
2. Summarize and track weekly developments in `pydantic`
3. Help me / our team organize and prioritize issues

This week is a holiday week in the US, so I and other members of our team will be out on Thursday / Friday. Thus, the plan for this week is a bit scaled back to accommodate the shorter work week. I'll also note, I'm on holiday next week, so won't be doing much more than some basic maintenance every few days.

## News

* We've surpassed 200M downloads / month 🎈!

### PRs

* https://github.com/pydantic/pydantic/pull/9743
* https://github.com/pydantic/pydantic/pull/9771

### Contributors

Thanks to @nix010 for the awesome work on a variety of bug fixes, across both `pydantic` and `pydantic-core`!
Thanks to @dAIsySHEng1 for her dedicated docs improvement initiatives!

## My plans for this week

Generally, I'll be focusing on the rollout of v2.8.0 and planning our next release sprint. This week will be a bit less technical than others, but will hopefully set the stage for some exciting weeks of development coming up.

- [x] Release v2.8.0 and publish the associated blog post
- [x] Fix our `relnotes-xxx` tag application automation on PRs, it's driving me nuts 🥜 
- [x] Move to `ruff v0.5.0` + modify [`pytest-examples`](https://pypi.org/project/pytest-examples/) to support said version as well, done via https://github.com/pydantic/pydantic/pull/9801
- [x] Finish up merging `json_schema_extra` via https://github.com/pydantic/pydantic/pull/9792
- [x] Fix handling of fractional components for timestamps in `speedate`, to go into v2.8.1 release
- [x] Write a plan (issue) for v2.9.0, emphasizing performance improvements (startup time), union serialization fixes, and potentially some enum issues
- [x] Release v2.8.1 with any critical bug fixes by the end of the week
- [ ] Backlog grooming for both `pydantic` and `pydantic-core`, as well as issue categorization to support easy access / entry for new contributors

I would love to dig into https://github.com/pydantic/pydantic/issues/9688, but I'm not sure how much time will be left this week for that. This is dependent on the amount of work needed for v2.8 patch releases. I should have an update mid-week on this. UPDATE: I'm predicting not having time for this during the week, but this will be my top priority upon return.

## Review Queue

- [x] https://github.com/pydantic/pydantic/pull/9787
- [x] https://github.com/pydantic/pydantic/pull/9764
- [x] https://github.com/pydantic/pydantic-core/pull/1349
- [x] pending `codeflash` PRs
- [x] https://github.com/pydantic/pydantic/pull/9797
- [x] https://github.com/pydantic/pydantic/pull/9796
- [ ] https://github.com/pydantic/pydantic-core/pull/1351
- [ ] https://github.com/pydantic/pydantic/pull/9770
- [ ] https://github.com/pydantic/pydantic/pull/9654 (and associated work in `pydantic-core`)

## Feedback

I'd love to get some feedback from the community / other contributors here. What else would be helpful for you to see on weekly reports like these?

Other sections I think could be valuable:
* high priority issues
* good first issues

**Comment by sydney-runkle** [comment]
@hramezani and @Kludex,

Confirmed, I finally fixed the relnotes application thing. Here's a PR with proof: https://github.com/pydantic/pydantic/pull/9814

**Comment by sydney-runkle** [comment]
My work for this week will be catching up on everything I missed over my holiday, then will pivot to another weekly plan next Monday!
