### ISSUE TITLE
`pydantic` weekly project plan (Sydney Runkle) - July 22nd, 2024

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#9933]
## Background

Following on the heels of #9804, from before my time off, I'm going to continue with this public weekly plan approach.

The motivation behind tickets like these is to:

1. Communicate and coordinate with the community
2. Summarize and track weekly developments in `pydantic`
3. Help me / our team organize and prioritize issues

### Contributors

Thanks to @tlambert03 for the variety of bug fixes and new features contributed recently!
Thanks to @dmontagu for his rapid `mypy` fix contributions last week!
Thanks to @Viicos for helping to answer so many issues while I was away!

## My plans for this week

We've release v2.8.2, and are pivoting our focus to v2.9.0. I've laid out the plan for that release in #9834. My main focus this week is going to be on improving the schema building process in `pydantic`, with an emphasis on improved performance and import times for models.

In order to improve performance, I'm working on the following:

1. Profiling code for a variety of cases - complex models, simple models, `pydantic` imports, etc. I'm trying to identify where the most significant bottlenecks are, and where we're doing more than we need to in terms of schema building.
2. Exploring various ways to change the internals of our schema building process. Through this, I'll document other notes on potential improvements that might not be directly be related to performance, but are instead structurally or conceptually valuable.

Some specific issues that relate to this are:

* https://github.com/pydantic/pydantic/issues/9340
* https://github.com/pydantic/pydantic/issues/9908
* In general, addressing these: https://github.com/pydantic/pydantic/labels/performance

Other items:

- [ ] Backlog grooming for both `pydantic` and `pydantic-core`, as well as issue categorization to support easy access / entry for new contributors - pushing this to next week, perhaps with a contributing docs update as well
- [x] It seems as though some folks have had difficulty downloading `pydantic v2.8.X` due to issues with `pydantic-core` builds, I'd love to get to the bottom of this - update, @davidhewitt is on the case
- [ ] Throughout the week, I'd like to pick up 3-5 small bugs to fix in `pydantic` between performance focused sessions. Will survey the issue board for bite size pieces.
- [ ] As always, a weekly docs update PR based on incoming requests, including https://github.com/pydantic/pydantic/issues/9956

I've put https://github.com/pydantic/pydantic/issues/9688 on the back burner for this week, but it's still a top priority for v2.9.0.

### `pydantic`

- [x] https://github.com/pydantic/pydantic/pull/9932
- [ ] https://github.com/pydantic/pydantic/pull/9912 (on hold until tomorrow's oss meeting)
- [x] https://github.com/pydantic/pydantic/pull/9896 (waiting for author revision, minor change)
- [x] https://github.com/pydantic/pydantic/pull/9863 (waiting for author revision)
- [ ] https://github.com/pydantic/pydantic/pull/9770 (waiting for author revision)

### `pydantic-core`

- [x] https://github.com/pydantic/pydantic-core/pull/1372
- [x] https://github.com/pydantic/pydantic-core/pull/1373 (waiting for feedback from samuel or david)
- [ ] https://github.com/pydantic/pydantic-core/pull/1369 (on hold)
- [ ] https://github.com/pydantic/pydantic-core/pull/1359 (on hold)

## Feedback

I'd love to get some feedback from the community / other contributors here. What else would be helpful for you to see on weekly reports like these?

Other sections I think could be valuable:
* high priority issues
* good first issues

**Comment by sydney-runkle** [comment]
More things for reviewing:
- [x] https://github.com/pydantic/pydantic/pull/9972
- [ ] https://github.com/pydantic/pydantic/pull/9971

**Comment by sydney-runkle** [comment]
I've added some additional tracking for my work this week here:

https://github.com/pydantic/pydantic/issues/9965

**Comment by sydney-runkle** [comment]
Didn't get to as many of the smaller tasks as I'd hoped this week, but made some good headway on `_generate_schema.py` refactoring, which I find to be relatively high priority given the performance impact.
