### ISSUE TITLE
pydantic weekly project plan (Sydney Runkle) - July 29th, 2024

### ISSUE THREAD

**Issue by sydney-runkle** [pydantic/pydantic#9994]
## Background

Following on the heels of #9933, I'm going to continue with this public weekly plan approach.

The motivation behind tickets like these is to:

1. Communicate and coordinate with the community
2. Summarize and track weekly developments in `pydantic`
3. Help me / our team organize and prioritize issues

### Contributors

Thanks to @ kc0506 for the variety of bug fixes contributed recently!
Thanks to @ misrasaurabh1 from the codeflash team for the help with optimizations in the `_generate_schema.py` file!

## My plans for this week

This will be my second week focusing on improving schema build time in `pydantic`, with an emphasis on improved performance and import times for models. I anticipate this being my last week where this is my primary focus.

In order to improve performance, I'm working on the following:

1. Profiling code for a variety of cases - complex models, simple models, `pydantic` imports, etc. I'm trying to identify where the most significant bottlenecks are, and where we're doing more than we need to in terms of schema building. I'm also using benchmarks to track the progress made on each of my PRs.
2. Exploring various ways to change the internals of our schema building process. Through this, I'll document other notes on potential improvements that might not be directly be related to performance, but are instead structurally or conceptually valuable.

Some specific issues that relate to this are:

* https://github.com/pydantic/pydantic/issues/9340 - I will consider this as closed once I make some more changes to our `deque` schema, I think things are in a much better state than they were last week
* https://github.com/pydantic/pydantic/issues/9908
* In general, addressing these: https://github.com/pydantic/pydantic/labels/performance

Other items:

- [ ] Backlog grooming for both `pydantic` and `pydantic-core`, as well as issue categorization to support easy access / entry for new contributors
- [ ] Writing up documentation for new contributors related to the architecture / interaction between `pydantic` and `pydantic-core`
- [ ] Last week I didn't get to a docs update PR, but I'll do one this week including https://github.com/pydantic/pydantic/issues/9956
- [ ] I mentioned that I'd take a closer look at https://github.com/pydantic/pydantic/issues/9969

I've put https://github.com/pydantic/pydantic/issues/9688 on the back burner for this week, but it's still a top priority for v2.9.0.

### `pydantic`

- [ ] [https://github.com/pydantic/pydantic/pull/9912
- [ ] https://github.com/pydantic/pydantic/pull/9770
- [ ] https://github.com/pydantic/pydantic-core/pull/1331
- [ ] https://github.com/pydantic/pydantic/pull/9990
- [x] https://github.com/pydantic/pydantic/pull/9863

### `pydantic-core`

- [ ] https://github.com/pydantic/pydantic-core/pull/1373
- [ ] https://github.com/pydantic/pydantic-core/pull/1369
- [ ] https://github.com/pydantic/pydantic-core/pull/1359

## Feedback

I'd love to get some feedback from the community / other contributors here. What else would be helpful for you to see on weekly reports like these?

Other sections I think could be valuable:
* high priority issues
* good first issues

**Comment by sydney-runkle** [comment]
I've updated the review queue with new PRs, will try to get through most of these by EOD today.

**Comment by sydney-runkle** [comment]
Pretty happy with this week's progress. Excited to have a more varied week next week in terms of some rust stuff / some Python stuff. After I work on our `_model_construction.py` smoking gun for performance, I'll pivot to union ser stuff. Hoping to start that by Wednesday at the latest.

**Comment by sydney-runkle** [comment]
PRs as a result of this week's work:

* https://github.com/pydantic/pydantic/pull/9979
* https://github.com/pydantic/pydantic/pull/9999
* https://github.com/pydantic/pydantic/pull/10003
* https://github.com/pydantic/pydantic/pull/10007
* https://github.com/pydantic/pydantic/pull/10009
* https://github.com/pydantic/pydantic/pull/10013
* https://github.com/pydantic/pydantic/pull/10018
* https://github.com/pydantic/pydantic/pull/10020
